include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    use_build_context_synchronously: true
    avoid_print: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
