include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
  exclude:
    - "build/**"
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    use_build_context_synchronously: true
    avoid_print: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    sort_pub_dependencies: false
    eol_at_end_of_file: false
    # Disable rules that don't make sense for animation-heavy Material 3 apps
    prefer_int_literals: false  # Double literals are fine for animations
    avoid_redundant_argument_values: false  # Explicit values improve readability
    unnecessary_breaks: false  # Breaks in switch statements improve readability
    cascade_invocations: false  # Not always better for canvas operations
    flutter_style_todos: false  # Standard TODO comments are fine
    lines_longer_than_80_chars: false  # Modern screens can handle longer lines
