targets:
  $default:
    builders:
      riverpod_generator|riverpod_generator:
        generate_for:
          - lib/**
        options:
          # Generate .g.dart files for Riverpod providers
          provider_name_suffix: "Provider"
          
      json_serializable|json_serializable:
        generate_for:
          - lib/models/**
        options:
          # JSON serialization options
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

global_options:
  # Exclude generated files from being processed again
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
