name: flutter_saas_template
description: Octo Vocab - Privacy-first vocabulary learning for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Firebase (deferred to later phases; removed for web run compatibility)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6
  # firebase_crashlytics: ^3.4.9
  
  # Navigation
  go_router: ^12.1.3
  go_router_builder: ^2.4.1
  
  # Data Models & JSON
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Local Storage (Privacy-First)
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  # Linting - Keep current version for stability
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/vocab/
    - assets/vocab/latin/
    - assets/vocab/latin/beginner/
    - assets/vocab/latin/intermediate/
    - assets/vocab/latin/advanced/
    - assets/vocab/spanish/
    - assets/vocab/spanish/beginner/
    - assets/vocab/spanish/intermediate/
    - assets/vocab/spanish/advanced/
